### PR TITLE
Hooked create incident

### PR DESCRIPTION
**Pull request by bisonlou**
This pull request incoporates functionality to:

- Register
- Login
- Create an incident

To test simply browse to https://bisonlou.github.io/ireporter/UI/login.html

### CODE REVIEW

**Comment by kalsmic** [comment]
@bisonlou, nice UI, very attractive and responsive as well. I was able to create both a red-flag and an incident record.

**A.O.B**
1. On the phone, the getting started button for sign up is not visible.
screenshot_20190211-101532
2. It will also be nice if you added placeholders for the sign-up form, I found it a bit confusing since the labels appeared below the input fields.

**Comment by bisonlou** [comment]
Thanks. Will definitely work on that.

**Comment by richien** [comment]
Wow, I really like the feel of your UI. Looks very professional. Good work. I was able to create an account, log in and create a red flag as well as view the recently created red flag on the home page.

**Comment by bisonlou** [comment]
Thanks Willis. You need to send me your link so I look at it and give
feedback.


*Kind Regards*
*    Innocent Lou*

+256 753-669-897

**Pull request merged**
